/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './index.html',
    './Hub.html',
    './Hub/**/*.html',
    './Hub/**/*.ts',
    './src/**/*.ts',
    './src/partials/**/*.html',
  ],
  theme: {
    extend: {
      colors: {
        'on-background': '#dae2fd',
        'surface-bright': '#31394d',
        'surface': '#0b1326',
        'on-surface': '#dae2fd',
        'tertiary': '#adc6ff',
        'on-surface-variant': '#cfc2d6',
        'surface-tint': '#ddb7ff',
        'surface-container-lowest': '#060e20',
        'secondary-container': '#00a572',
        'inverse-surface': '#dae2fd',
        'surface-variant': '#2d3449',
        'secondary': '#4edea3',
        'outline': '#988d9f',
        'error': '#ffb4ab',
        'inverse-primary': '#842bd2',
        'surface-container': '#171f33',
        'tertiary-container': '#4d8eff',
        'surface-dim': '#0b1326',
        'surface-container-highest': '#2d3449',
        'on-primary': '#490080',
        'surface-container-high': '#222a3d',
        'primary-container': '#b76dff',
        'primary': '#ddb7ff',
        'outline-variant': '#4d4354',
        'background': '#0b1326',
        'surface-container-low': '#131b2e',
        'on-primary-container': '#400071',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        md: '16px',
        lg: '24px',
        gutter: '24px',
        xs: '4px',
        sm: '8px',
        'container-max': '1440px',
        base: '8px',
        xl: '40px',
      },
      fontSize: {
        h1: ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        h2: ['30px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        h3: ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
